In [ ]:
import pandas as pd
import sqlite3
import os
import zipfile # Needed for zip extraction

conn = sqlite3.connect("maven_fuzzy_factory.db")

data_dir = 'maven_data'
zip_file_name = 'Maven+Fuzzy+Factory.zip' # Assuming this is the name of the uploaded zip file

# Ensure the data directory exists and contains files
if not os.path.exists(data_dir) or not os.listdir(data_dir):
    print(f"Directory '{data_dir}' is missing or empty. Attempting to extract '{zip_file_name}'.")
    if os.path.exists(zip_file_name):
        try:
            os.makedirs(data_dir, exist_ok=True) # Ensure directory exists before extraction
            with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
                zip_ref.extractall(data_dir)
            print(f"Successfully extracted '{zip_file_name}' to '{data_dir}'.")
        except Exception as e:
            print(f"Error extracting zip file: {e}")
            print("Please ensure the zip file is uploaded and valid.")
    else:
        print(f"Error: Zip file '{zip_file_name}' not found. Please upload the data zip file using cell KtFbPyP6moj7 first.")

# If directory exists and has content (either initially or after extraction attempt), proceed to load tables
if os.path.exists(data_dir) and os.listdir(data_dir):
    for file in os.listdir(data_dir):
        if file.endswith('.csv') and file != 'maven_fuzzy_factory_data_dictionary.csv':
            table_name = file.replace('.csv', '')
            df = pd.read_csv(os.path.join(data_dir, file))
            df.to_sql(table_name, conn, if_exists='replace', index=False)
    print("Database connection established and tables re-loaded.")
else:
    print("Could not establish database connection with tables as data directory is still not ready.")

Directory 'maven_data' is missing or empty. Attempting to extract 'Maven+Fuzzy+Factory.zip'.
Error: Zip file 'Maven+Fuzzy+Factory.zip' not found. Please upload the data zip file using cell KtFbPyP6moj7 first.
Could not establish database connection with tables as data directory is still not ready.

In [ ]:
import pandas as pd
import sqlite3
import os
import zipfile

# Check whether maven_data already exists
if not os.path.exists("maven_data"):

    print("📁 maven_data folder not found.")
    print("Please select Maven+Fuzzy+Factory.zip")

    from google.colab import files
    uploaded = files.upload()

    # Find the uploaded ZIP file
    zip_file = [f for f in uploaded.keys() if f.endswith(".zip")][0]

    # Extract it
    with zipfile.ZipFile(zip_file, "r") as zip_ref:
        zip_ref.extractall("maven_data")

    print("✅ ZIP extracted successfully!")

# Connect to SQLite
conn = sqlite3.connect("maven_fuzzy_factory.db")

# Load CSV files into SQLite
for file in os.listdir("maven_data"):

    if file.endswith(".csv") and file != "maven_fuzzy_factory_data_dictionary.csv":

        df = pd.read_csv("maven_data/" + file)

        table_name = file.replace(".csv", "")

        df.to_sql(
            table_name,
            conn,
            if_exists="replace",
            index=False
        )

        print(f"✅ {table_name} loaded — {len(df)} rows")

print("\n🎉 DATABASE READY!")

📁 maven_data folder not found.
Please select Maven+Fuzzy+Factory.zip

Saving Maven+Fuzzy+Factory.zip to Maven+Fuzzy+Factory.zip
✅ ZIP extracted successfully!
✅ products loaded — 4 rows
✅ order_item_refunds loaded — 1731 rows
✅ website_sessions loaded — 472871 rows
✅ orders loaded — 32313 rows
✅ order_items loaded — 40025 rows
✅ website_pageviews loaded — 1188124 rows

🎉 DATABASE READY!

In [ ]:
tables = pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type = 'table';
""", conn)

display(tables)

                 name
0            products
1  order_item_refunds
2    website_sessions
3              orders
4         order_items
5   website_pageviews

In [ ]:
def sql(query):
    return pd.read_sql_query(query, conn)

In [ ]:
sql("""
SELECT website_session_id
FROM website_sessions;
""")

        website_session_id
0                        1
1                        2
2                        3
3                        4
4                        5
...                    ...
472866              472867
472867              472868
472868              472869
472869              472870
472870              472871

[472871 rows x 1 columns]

In [ ]:
sql("""
SELECT website_session_id, user_id
FROM website_sessions;
""")

        website_session_id  user_id
0                        1        1
1                        2        2
2                        3        3
3                        4        4
4                        5        5
...                    ...      ...
472866              472867   394314
472867              472868   394315
472868              472869   394316
472869              472870   394317
472870              472871   394318

[472871 rows x 2 columns]

In [ ]:
sql("PRAGMA table_info(products);")

   cid          name     type  notnull dflt_value  pk
0    0    product_id  INTEGER        0       None   0
1    1    created_at     TEXT        0       None   0
2    2  product_name     TEXT        0       None   0

In [ ]:
sql("""
SELECT product_name
FROM products;
""")

                 product_name
0      The Original Mr. Fuzzy
1       The Forever Love Bear
2    The Birthday Sugar Panda
3  The Hudson River Mini bear

In [ ]:
sql("""
PRAGMA table_info(website_sessions);
""")

   cid                name     type  notnull dflt_value  pk
0    0  website_session_id  INTEGER        0       None   0
1    1          created_at     TEXT        0       None   0
2    2             user_id  INTEGER        0       None   0
3    3   is_repeat_session  INTEGER        0       None   0
4    4          utm_source     TEXT        0       None   0
5    5        utm_campaign     TEXT        0       None   0
6    6         utm_content     TEXT        0       None   0
7    7         device_type     TEXT        0       None   0
8    8        http_referer     TEXT        0       None   0

In [ ]:
sql("""
PRAGMA table_info(order_items_refunds);
""")

Empty DataFrame
Columns: [cid, name, type, notnull, dflt_value, pk]
Index: []

In [ ]:
sql("""
PRAGMA table_info(order_items);
""")

   cid             name     type  notnull dflt_value  pk
0    0    order_item_id  INTEGER        0       None   0
1    1       created_at     TEXT        0       None   0
2    2         order_id  INTEGER        0       None   0
3    3       product_id  INTEGER        0       None   0
4    4  is_primary_item  INTEGER        0       None   0
5    5        price_usd     REAL        0       None   0
6    6         cogs_usd     REAL        0       None   0

In [ ]:
sql("""
PRAGMA table_info(orders);
""")

   cid                name     type  notnull dflt_value  pk
0    0            order_id  INTEGER        0       None   0
1    1          created_at     TEXT        0       None   0
2    2  website_session_id  INTEGER        0       None   0
3    3             user_id  INTEGER        0       None   0
4    4  primary_product_id  INTEGER        0       None   0
5    5     items_purchased  INTEGER        0       None   0
6    6           price_usd     REAL        0       None   0
7    7            cogs_usd     REAL        0       None   0

In [ ]:
sql("""
PRAGMA table_info(website_pageviews);
""")

   cid                 name     type  notnull dflt_value  pk
0    0  website_pageview_id  INTEGER        0       None   0
1    1           created_at     TEXT        0       None   0
2    2   website_session_id  INTEGER        0       None   0
3    3         pageview_url     TEXT        0       None   0

In [ ]:
sql ("""
SELECT product_id
FROM products;
""")

   product_id
0           1
1           2
2           3
3           4

In [ ]:
sql ("""
SELECT created_at
FROM products;
""")

            created_at
0  2012-03-19 08:00:00
1  2013-01-06 13:00:00
2  2013-12-12 09:00:00
3  2014-02-05 10:00:00

In [ ]:
sql("""
SELECT product_id,product_name,created_at
FROM products;
""")

   product_id                product_name           created_at
0           1      The Original Mr. Fuzzy  2012-03-19 08:00:00
1           2       The Forever Love Bear  2013-01-06 13:00:00
2           3    The Birthday Sugar Panda  2013-12-12 09:00:00
3           4  The Hudson River Mini bear  2014-02-05 10:00:00

In [ ]:
print(conn)
print(conn.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall())

<sqlite3.Connection object at 0x7f7fd1e09e40>
[('products',), ('order_item_refunds',), ('website_sessions',), ('orders',), ('order_items',), ('website_pageviews',)]

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'maven_data', 'Maven+Fuzzy+Factory.zip', 'maven_fuzzy_factory.db', 'sample_data']

In [ ]:
sql ("""
SELECT created_at
FROM website_sessions;
""")

                 created_at
0       2012-03-19 08:04:16
1       2012-03-19 08:16:49
2       2012-03-19 08:26:55
3       2012-03-19 08:37:33
4       2012-03-19 09:00:55
...                     ...
472866  2015-03-19 07:49:25
472867  2015-03-19 07:54:36
472868  2015-03-19 07:55:40
472869  2015-03-19 07:56:29
472870  2015-03-19 07:59:08

[472871 rows x 1 columns]

In [ ]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("maven_fuzzy_factory.db")

def sql(query):
    return pd.read_sql_query(query, conn)

In [ ]:
sql("""
SELECT created_at
FROM website_sessions;
""")

                 created_at
0       2012-03-19 08:04:16
1       2012-03-19 08:16:49
2       2012-03-19 08:26:55
3       2012-03-19 08:37:33
4       2012-03-19 09:00:55
...                     ...
472866  2015-03-19 07:49:25
472867  2015-03-19 07:54:36
472868  2015-03-19 07:55:40
472869  2015-03-19 07:56:29
472870  2015-03-19 07:59:08

[472871 rows x 1 columns]

In [ ]:
sql ("""
SELECT is_repeat_session
FROM website_sessions;
""")

        is_repeat_session
0                       0
1                       0
2                       0
3                       0
4                       0
...                   ...
472866                  0
472867                  0
472868                  0
472869                  0
472870                  0

[472871 rows x 1 columns]

In [ ]:
sql ("""
SELECT utm_source,utm_campaign,utm_content
FROM website_sessions;
""")

       utm_source utm_campaign utm_content
0         gsearch     nonbrand      g_ad_1
1         gsearch     nonbrand      g_ad_1
2         gsearch     nonbrand      g_ad_1
3         gsearch     nonbrand      g_ad_1
4         gsearch     nonbrand      g_ad_1
...           ...          ...         ...
472866    gsearch        brand      g_ad_2
472867    bsearch     nonbrand      b_ad_1
472868    gsearch     nonbrand      g_ad_1
472869    gsearch     nonbrand      g_ad_1
472870       None         None        None

[472871 rows x 3 columns]

In [ ]:
sql("""
SELECT device_type,http_referer
FROM website_sessions;
""")

       device_type             http_referer
0           mobile  https://www.gsearch.com
1          desktop  https://www.gsearch.com
2          desktop  https://www.gsearch.com
3          desktop  https://www.gsearch.com
4           mobile  https://www.gsearch.com
...            ...                      ...
472866     desktop  https://www.gsearch.com
472867      mobile  https://www.bsearch.com
472868      mobile  https://www.gsearch.com
472869     desktop  https://www.gsearch.com
472870      mobile                     None

[472871 rows x 2 columns]

In [ ]:
sql ("""
SELECT device_type
FROM website_sessions
WHERE device_type = 'desktop';
""")

       device_type
0          desktop
1          desktop
2          desktop
3          desktop
4          desktop
...            ...
327022     desktop
327023     desktop
327024     desktop
327025     desktop
327026     desktop

[327027 rows x 1 columns]

In [ ]:
sql("""
SELECT website_session_id, user_id, utm_source
FROM website_sessions
WHERE utm_source = 'gsearch';
""")

        website_session_id  user_id utm_source
0                        1        1    gsearch
1                        2        2    gsearch
2                        3        3    gsearch
3                        4        4    gsearch
4                        5        5    gsearch
...                    ...      ...        ...
316030              472865   394312    gsearch
316031              472866   394313    gsearch
316032              472867   394314    gsearch
316033              472869   394316    gsearch
316034              472870   394317    gsearch

[316035 rows x 3 columns]

In [ ]:
sql("""
SELECT created_at
FROM website_sessions
ORDER BY created_at DESC;
""")

                 created_at
0       2015-03-19 07:59:08
1       2015-03-19 07:56:29
2       2015-03-19 07:55:40
3       2015-03-19 07:54:36
4       2015-03-19 07:49:25
...                     ...
472866  2012-03-19 09:00:55
472867  2012-03-19 08:37:33
472868  2012-03-19 08:26:55
472869  2012-03-19 08:16:49
472870  2012-03-19 08:04:16

[472871 rows x 1 columns]

In [ ]:
sql("""
SELECT DISTINCT device_type
FROM website_sessions;
""")

  device_type
0      mobile
1     desktop

In [ ]:
sql("""
SELECT DISTINCT utm_source
FROM website_sessions;
""")

   utm_source
0     gsearch
1        None
2     bsearch
3  socialbook

In [ ]:
sql("""
SELECT
    website_sessions.website_session_id,
    website_sessions.user_id,
    orders.order_id
FROM website_sessions
JOIN orders
    ON website_sessions.website_session_id = orders.website_session_id;
""")

       website_session_id  user_id  order_id
0                      20       20         1
1                     104      104         2
2                     147      147         3
3                     160      160         4
4                     177      177         5
...                   ...      ...       ...
32308              472795   394255     32309
32309              472798   394257     32310
32310              472809   394268     32311
32311              472814   394273     32312
32312              472818   386000     32313

[32313 rows x 3 columns]

In [ ]:
sql ("""
SELECT order_item_id,created_at,order_id
FROM order_items;
""")

       order_item_id           created_at  order_id
0                  1  2012-03-19 10:42:46         1
1                  2  2012-03-19 19:27:37         2
2                  3  2012-03-20 06:44:45         3
3                  4  2012-03-20 09:41:45         4
4                  5  2012-03-20 11:28:15         5
...              ...                  ...       ...
40020          40021  2015-03-19 04:10:43     32310
40021          40022  2015-03-19 05:27:28     32311
40022          40023  2015-03-19 05:27:28     32311
40023          40024  2015-03-19 05:35:57     32312
40024          40025  2015-03-19 05:38:31     32313

[40025 rows x 3 columns]

In [ ]:
sql ("""
SELECT order_item_id,created_at,order_id
FROM order_items
ORDER BY created_at DESC;
""")

       order_item_id           created_at  order_id
0              40025  2015-03-19 05:38:31     32313
1              40024  2015-03-19 05:35:57     32312
2              40022  2015-03-19 05:27:28     32311
3              40023  2015-03-19 05:27:28     32311
4              40021  2015-03-19 04:10:43     32310
...              ...                  ...       ...
40020              5  2012-03-20 11:28:15         5
40021              4  2012-03-20 09:41:45         4
40022              3  2012-03-20 06:44:45         3
40023              2  2012-03-19 19:27:37         2
40024              1  2012-03-19 10:42:46         1

[40025 rows x 3 columns]

In [ ]:
sql ("""
SELECT product_id,is_primary_item
FROM order_items
""")

       product_id  is_primary_item
0               1                1
1               1                1
2               1                1
3               1                1
4               1                1
...           ...              ...
40020           4                1
40021           2                1
40022           4                0
40023           4                1
40024           1                1

[40025 rows x 2 columns]

In [ ]:
sql ("""
SELECT price_usd,cogs_usd
FROM order_items;
""")

       price_usd  cogs_usd
0          49.99     19.49
1          49.99     19.49
2          49.99     19.49
3          49.99     19.49
4          49.99     19.49
...          ...       ...
40020      29.99      9.49
40021      59.99     22.49
40022      29.99      9.49
40023      29.99      9.49
40024      49.99     19.49

[40025 rows x 2 columns]

In [ ]:
sql ("""
SELECT price_usd,cogs_usd
FROM order_items
ORDER BY price_usd DESC;
""")

       price_usd  cogs_usd
0          59.99     22.49
1          59.99     22.49
2          59.99     22.49
3          59.99     22.49
4          59.99     22.49
...          ...       ...
40020      29.99      9.49
40021      29.99      9.49
40022      29.99      9.49
40023      29.99      9.49
40024      29.99      9.49

[40025 rows x 2 columns]

In [ ]:
sql ("""
SELECT price_usd,cogs_usd
FROM order_items
ORDER BY price_usd ASC
""")

       price_usd  cogs_usd
0          29.99      9.49
1          29.99      9.49
2          29.99      9.49
3          29.99      9.49
4          29.99      9.49
...          ...       ...
40020      59.99     22.49
40021      59.99     22.49
40022      59.99     22.49
40023      59.99     22.49
40024      59.99     22.49

[40025 rows x 2 columns]

In [ ]:
sql ("""
SELECT price_usd,cogs_usd
FROM order_items
WHERE price_usd > 20;
""")

       price_usd  cogs_usd
0          49.99     19.49
1          49.99     19.49
2          49.99     19.49
3          49.99     19.49
4          49.99     19.49
...          ...       ...
40020      29.99      9.49
40021      59.99     22.49
40022      29.99      9.49
40023      29.99      9.49
40024      49.99     19.49

[40025 rows x 2 columns]

In [ ]:
sql("""
SELECT DISTINCT product_id,is_primary_item,order_id,price_usd,cogs_usd
FROM order_items
""")

       product_id  is_primary_item  order_id  price_usd  cogs_usd
0               1                1         1      49.99     19.49
1               1                1         2      49.99     19.49
2               1                1         3      49.99     19.49
3               1                1         4      49.99     19.49
4               1                1         5      49.99     19.49
...           ...              ...       ...        ...       ...
40020           4                1     32310      29.99      9.49
40021           2                1     32311      59.99     22.49
40022           4                0     32311      29.99      9.49
40023           4                1     32312      29.99      9.49
40024           1                1     32313      49.99     19.49

[40025 rows x 5 columns]

In [ ]:
sql("""
SELECT COUNT(*) AS total_items
FROM order_items;
""")

   total_items
0        40025

In [ ]:
sql("""
SELECT SUM(price_usd) AS total_revenue
FROM order_items;
""")

   total_revenue
0     1938509.75

In [ ]:
sql("""
SELECT
    MIN(price_usd) AS cheapest,
    MAX(price_usd) AS most_expensive
FROM order_items;
""")

   cheapest  most_expensive
0     29.99           59.99

In [ ]:
sql("""
SELECT
    product_id,
    price_usd,
    cogs_usd,
    price_usd - cogs_usd AS profit
FROM order_items;
""")

       product_id  price_usd  cogs_usd  profit
0               1      49.99     19.49    30.5
1               1      49.99     19.49    30.5
2               1      49.99     19.49    30.5
3               1      49.99     19.49    30.5
4               1      49.99     19.49    30.5
...           ...        ...       ...     ...
40020           4      29.99      9.49    20.5
40021           2      59.99     22.49    37.5
40022           4      29.99      9.49    20.5
40023           4      29.99      9.49    20.5
40024           1      49.99     19.49    30.5

[40025 rows x 4 columns]

In [ ]:
sql("""
SELECT
    product_id,
    SUM(price_usd) AS total_revenue
FROM order_items
GROUP BY product_id;
""")

   product_id  total_revenue
0           1     1211057.74
1           2      347702.04
2           3      229260.15
3           4      150489.82

In [ ]:
sql("""
SELECT
    product_id,
    SUM(price_usd) AS total_revenue
FROM order_items
GROUP BY product_id
ORDER BY total_revenue DESC;
""")

   product_id  total_revenue
0           1     1211057.74
1           2      347702.04
2           3      229260.15
3           4      150489.82

In [ ]:
sql("""
SELECT order_id,created_at,website_session_id,user_id
FROM orders;
""")

       order_id           created_at  website_session_id  user_id
0             1  2012-03-19 10:42:46                  20       20
1             2  2012-03-19 19:27:37                 104      104
2             3  2012-03-20 06:44:45                 147      147
3             4  2012-03-20 09:41:45                 160      160
4             5  2012-03-20 11:28:15                 177      177
...         ...                  ...                 ...      ...
32308     32309  2015-03-19 03:58:12              472795   394255
32309     32310  2015-03-19 04:10:43              472798   394257
32310     32311  2015-03-19 05:27:28              472809   394268
32311     32312  2015-03-19 05:35:57              472814   394273
32312     32313  2015-03-19 05:38:31              472818   386000

[32313 rows x 4 columns]

In [ ]:
sql("""
SELECT DISTINCT order_id,created_at,website_session_id,user_id
FROM orders;
""")

       order_id           created_at  website_session_id  user_id
0             1  2012-03-19 10:42:46                  20       20
1             2  2012-03-19 19:27:37                 104      104
2             3  2012-03-20 06:44:45                 147      147
3             4  2012-03-20 09:41:45                 160      160
4             5  2012-03-20 11:28:15                 177      177
...         ...                  ...                 ...      ...
32308     32309  2015-03-19 03:58:12              472795   394255
32309     32310  2015-03-19 04:10:43              472798   394257
32310     32311  2015-03-19 05:27:28              472809   394268
32311     32312  2015-03-19 05:35:57              472814   394273
32312     32313  2015-03-19 05:38:31              472818   386000

[32313 rows x 4 columns]

In [ ]:
sql("""
SELECT COUNT (DISTINCT order_id) AS total_orders
FROM orders;
""")

   total_orders
0         32313

In [ ]:
sql("""
SELECT
    MIN(price_usd) AS cheapest,
    MAX(price_usd) AS most_expensive
FROM orders;
""")

   cheapest  most_expensive
0     29.99          109.98

In [ ]:
sql("""
SELECT price_usd,cogs_usd
FROM orders
ORDER BY price_usd DESC;
""")

       price_usd  cogs_usd
0         109.98     41.98
1         109.98     41.98
2         109.98     41.98
3         109.98     41.98
4         109.98     41.98
...          ...       ...
32308      29.99      9.49
32309      29.99      9.49
32310      29.99      9.49
32311      29.99      9.49
32312      29.99      9.49

[32313 rows x 2 columns]

In [ ]:
sql("""
SELECT AVG(price_usd) AS average_price
FROM orders;
""")

   average_price
0      59.991636

In [ ]:
sql("""
SELECT SUM(price_usd) AS total_revenue
FROM order_items;
""")

   total_revenue
0     1938509.75

In [ ]:
sql("""
SELECT
    user_id,
    COUNT(*) AS total_orders
FROM orders
GROUP BY user_id;
""")

       user_id  total_orders
0           13             1
1           20             1
2           59             1
3          104             1
4          147             1
...        ...           ...
31691   394231             1
31692   394255             1
31693   394257             1
31694   394268             1
31695   394273             1

[31696 rows x 2 columns]

In [ ]:
sql("""
SELECT
    user_id,
    COUNT(*) AS total_orders
FROM orders
GROUP BY user_id
HAVING COUNT(*) > 2;
""")

    user_id  total_orders
0     24159             3
1     68624             3
2     69639             3
3     83383             3
4     99029             3
5    107850             3
6    122640             3
7    142410             3
8    157480             3
9    158032             3
10   158790             3
11   172266             3
12   248399             3
13   273501             3
14   275098             3
15   276897             3
16   289300             3
17   318660             3
18   324814             3
19   335300             3
20   336150             3
21   339124             3
22   341972             3
23   344087             3
24   358519             3
25   371472             3

In [ ]:
sql("""
SELECT
    user_id,
    SUM(price_usd) AS total_spent
FROM orders
GROUP BY user_id
HAVING SUM(price_usd) > 100;
""")

      user_id  total_spent
0       24159       149.97
1       39643       109.98
2       51657       109.98
3       53233       109.98
4       57464       109.98
...       ...          ...
1512   391764       109.98
1513   392054       109.98
1514   392397       109.98
1515   393677       109.98
1516   394016       109.98

[1517 rows x 2 columns]

In [ ]:
sql("""
SELECT
    order_id,
    price_usd,
    CASE
        WHEN price_usd >= 50 THEN 'Expensive'
        WHEN price_usd >= 20 THEN 'Medium'
        ELSE 'Cheap'
    END AS price_category
FROM orders;
""")

       order_id  price_usd price_category
0             1      49.99         Medium
1             2      49.99         Medium
2             3      49.99         Medium
3             4      49.99         Medium
4             5      49.99         Medium
...         ...        ...            ...
32308     32309      49.99         Medium
32309     32310      29.99         Medium
32310     32311      89.98      Expensive
32311     32312      29.99         Medium
32312     32313      49.99         Medium

[32313 rows x 3 columns]

In [ ]:
sql("""
SELECT
    order_id,
    price_usd
FROM orders
WHERE price_usd > (
    SELECT AVG(price_usd)
    FROM orders
);
""")

      order_id  price_usd
0         7300     109.98
1         7302     109.98
2         7310     109.98
3         7352     109.98
4         7376     109.98
...        ...        ...
7707     32296      95.98
7708     32298      79.98
7709     32299      95.98
7710     32304      75.98
7711     32311      89.98

[7712 rows x 2 columns]

In [ ]:
sql("""
WITH user_orders AS (
    SELECT
        user_id,
        COUNT(*) AS total_orders
    FROM orders
    GROUP BY user_id
)

SELECT *
FROM user_orders
WHERE total_orders > 2;
""")

    user_id  total_orders
0     24159             3
1     68624             3
2     69639             3
3     83383             3
4     99029             3
5    107850             3
6    122640             3
7    142410             3
8    157480             3
9    158032             3
10   158790             3
11   172266             3
12   248399             3
13   273501             3
14   275098             3
15   276897             3
16   289300             3
17   318660             3
18   324814             3
19   335300             3
20   336150             3
21   339124             3
22   341972             3
23   344087             3
24   358519             3
25   371472             3

In [ ]:
sql("""
SELECT
    order_id,
    user_id,
    price_usd,
-    SUM(price_usd) OVER (
        PARTITION BY user_id
    ) AS user_total_spending
FROM orders;
""")

       order_id  user_id  price_usd  user_total_spending
0           152       13      49.99                49.99
1             1       20      49.99                49.99
2           132       59      49.99                49.99
3             2      104      49.99                49.99
4             3      147      49.99                49.99
...         ...      ...        ...                  ...
32308     32308   394231      49.99                49.99
32309     32309   394255      49.99                49.99
32310     32310   394257      29.99                29.99
32311     32311   394268      89.98                89.98
32312     32312   394273      29.99                29.99

[32313 rows x 4 columns]

In [ ]:
sql("""
SELECT website_pageview_id,created_at,website_session_id
FROM website_pageviews;
""")

         website_pageview_id           created_at  website_session_id
0                          1  2012-03-19 08:04:16                   1
1                          2  2012-03-19 08:16:49                   2
2                          3  2012-03-19 08:26:55                   3
3                          4  2012-03-19 08:37:33                   4
4                          5  2012-03-19 09:00:55                   5
...                      ...                  ...                 ...
1188119              1188120  2015-03-19 07:57:32              472866
1188120              1188121  2015-03-19 07:58:13              472870
1188121              1188122  2015-03-19 07:59:07              472866
1188122              1188123  2015-03-19 07:59:08              472871
1188123              1188124  2015-03-19 07:59:32              472868

[1188124 rows x 3 columns]

In [ ]:
sql("""
SELECT website_pageview_id, website_session_id, pageview_url
FROM website_pageviews;
""")

         website_pageview_id  website_session_id            pageview_url
0                          1                   1                   /home
1                          2                   2                   /home
2                          3                   3                   /home
3                          4                   4                   /home
4                          5                   5                   /home
...                      ...                 ...                     ...
1188119              1188120              472866               /shipping
1188120              1188121              472870  /the-original-mr-fuzzy
1188121              1188122              472866              /billing-2
1188122              1188123              472871                   /home
1188123              1188124              472868  /the-original-mr-fuzzy

[1188124 rows x 3 columns]

In [ ]:
sql("""
SELECT website_session_id, pageview_url
FROM website_pageviews
WHERE pageview_url = '/products';
""")

        website_session_id pageview_url
0                        6    /products
1                       15    /products
2                       16    /products
3                       18    /products
4                       20    /products
...                    ...          ...
261226              472865    /products
261227              472866    /products
261228              472867    /products
261229              472868    /products
261230              472870    /products

[261231 rows x 2 columns]

In [ ]:
sql("""
SELECT DISTINCT pageview_url
FROM website_pageviews;
""")

                   pageview_url
0                         /home
1                     /products
2        /the-original-mr-fuzzy
3                         /cart
4                     /shipping
5                      /billing
6     /thank-you-for-your-order
7                     /lander-1
8                    /billing-2
9        /the-forever-love-bear
10                    /lander-2
11                    /lander-3
12    /the-birthday-sugar-panda
13                    /lander-4
14                    /lander-5
15  /the-hudson-river-mini-bear

In [ ]:
sql("""
SELECT COUNT(*) AS total_pageviews
FROM website_pageviews;
""")

   total_pageviews
0          1188124

In [ ]:
sql("""
SELECT
    pageview_url,
    COUNT(*) AS total_views
FROM website_pageviews
GROUP BY pageview_url
ORDER BY total_views DESC;
""")

                   pageview_url  total_views
0                     /products       261231
1        /the-original-mr-fuzzy       162525
2                         /home       137576
3                     /lander-2       131170
4                         /cart        94953
5                     /lander-3        79000
6                     /lander-5        68166
7                     /shipping        64484
8                    /billing-2        48441
9                     /lander-1        47574
10    /thank-you-for-your-order        32313
11       /the-forever-love-bear        26033
12    /the-birthday-sugar-panda        19046
13                    /lander-4         9385
14                     /billing         3617
15  /the-hudson-river-mini-bear         2610

In [ ]:
sql("""
SELECT
    pageview_url,
    COUNT(DISTINCT website_session_id) AS unique_sessions
FROM website_pageviews
GROUP BY pageview_url
ORDER BY unique_sessions DESC;
""")

                   pageview_url  unique_sessions
0                     /products           261231
1        /the-original-mr-fuzzy           162525
2                         /home           137576
3                     /lander-2           131170
4                         /cart            94953
5                     /lander-3            79000
6                     /lander-5            68166
7                     /shipping            64484
8                    /billing-2            48441
9                     /lander-1            47574
10    /thank-you-for-your-order            32313
11       /the-forever-love-bear            26033
12    /the-birthday-sugar-panda            19046
13                    /lander-4             9385
14                     /billing             3617
15  /the-hudson-river-mini-bear             2610

In [ ]:
sql("""
SELECT
    p.product_name,
    COUNT(oi.order_item_id) AS items_sold,
    SUM(oi.price_usd) AS revenue,
    SUM(oi.cogs_usd) AS cogs,
    SUM(oi.price_usd - oi.cogs_usd) AS profit
FROM order_items AS oi
JOIN products AS p
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue DESC;
""")

                 product_name  items_sold     revenue       cogs    profit
0      The Original Mr. Fuzzy       24226  1211057.74  472164.74  738893.0
1       The Forever Love Bear        5796   347702.04  130352.04  217350.0
2    The Birthday Sugar Panda        4985   229260.15   72232.65  157027.5
3  The Hudson River Mini bear        5018   150489.82   47620.82  102869.0